import React, { useState, useEffect } from 'react';
import { Navbar } from './components/Navbar';
import { EntryForm } from './components/EntryForm';
import { DailyReport } from './components/DailyReport';
import { VehicleDatabase } from './components/VehicleDatabase';
import { RegisteredVehicle, LogEntry } from './types';
import { supabase } from './lib/supabase';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState('entry');
  
  const [registeredVehicles, setRegisteredVehicles] = useState<RegisteredVehicle[]>([]);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Fetch data from Supabase
  const fetchData = async () => {
    setIsLoading(true);
    try {
      // 1. Fetch Vehicles
      const { data: vehiclesData, error: vehiclesError } = await supabase
        .from('vehicles')
        .select('*')
        .order('added_at', { ascending: false });

      if (vehiclesError) throw vehiclesError;

      // Map snake_case (DB) to camelCase (App)
      const formattedVehicles: RegisteredVehicle[] = (vehiclesData || []).map((v: any) => ({
        id: v.id,
        plateNumber: v.plate_number,
        ownerName: v.owner_name,
        department: v.department,
        addedAt: v.added_at
      }));
      setRegisteredVehicles(formattedVehicles);

      // 2. Fetch Logs
      const { data: logsData, error: logsError } = await supabase
        .from('logs')
        .select('*')
        .order('timestamp', { ascending: false });

      if (logsError) throw logsError;

      const formattedLogs: LogEntry[] = (logsData || []).map((l: any) => ({
        id: l.id,
        plateNumber: l.plate_number,
        direction: l.direction,
        vehicleType: l.vehicle_type,
        timestamp: l.timestamp,
        note: l.note,
        imageUrl: l.image_url
      }));
      setLogs(formattedLogs);

    } catch (error) {
      console.error("Error fetching data:", error);
      alert("เกิดข้อผิดพลาดในการดึงข้อมูลจากฐานข้อมูล");
    } finally {
      setIsLoading(false);
    }
  };

  // Initial Load
  useEffect(() => {
    fetchData();
  }, []);

  const handleAddLog = async (log: LogEntry) => {
    try {
      // Optimistic Update (Show immediately)
      setLogs(prev => [log, ...prev]);

      const { error } = await supabase.from('logs').insert({
        plate_number: log.plateNumber,
        direction: log.direction,
        vehicle_type: log.vehicleType,
        timestamp: log.timestamp,
        image_url: log.imageUrl
      });

      if (error) {
        console.error("Error adding log:", error);
        // Revert on error or fetch fresh data
        fetchData(); 
        alert("บันทึกข้อมูลไม่สำเร็จ");
      } else {
        // Optional: Fetch fresh data to get the real ID generated by DB
        // fetchData(); 
      }
    } catch (err) {
      console.error(err);
    }
  };

  const handleAddVehicle = async (vehicle: RegisteredVehicle) => {
    try {
      // Insert into DB
      const { data, error } = await supabase
        .from('vehicles')
        .insert({
          plate_number: vehicle.plateNumber,
          owner_name: vehicle.ownerName,
          department: vehicle.department,
          added_at: vehicle.addedAt
        })
        .select(); // Return the inserted row to get ID

      if (error) throw error;

      if (data) {
        const newVehicle = {
          id: data[0].id,
          plateNumber: data[0].plate_number,
          ownerName: data[0].owner_name,
          department: data[0].department,
          addedAt: data[0].added_at
        };
        setRegisteredVehicles(prev => [newVehicle, ...prev]);
      }
    } catch (error) {
      console.error("Error adding vehicle:", error);
      alert("ไม่สามารถเพิ่มข้อมูลรถได้ (อาจมีเลขทะเบียนซ้ำ)");
    }
  };

  const handleRemoveVehicle = async (id: string) => {
    try {
      const { error } = await supabase
        .from('vehicles')
        .delete()
        .eq('id', id);

      if (error) throw error;

      setRegisteredVehicles(prev => prev.filter(v => v.id !== id));
    } catch (error) {
      console.error("Error deleting vehicle:", error);
      alert("ลบข้อมูลไม่สำเร็จ");
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-slate-100 text-slate-500 gap-4">
        <div className="w-12 h-12 border-4 border-security-500 border-t-transparent rounded-full animate-spin"></div>
        <p>กำลังเชื่อมต่อฐานข้อมูล...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-100">
      <Navbar activeTab={activeTab} setActiveTab={setActiveTab} />
      
      <main className="pt-6">
        {activeTab === 'entry' && (
          <EntryForm 
            registeredVehicles={registeredVehicles} 
            onAddLog={handleAddLog} 
          />
        )}
        
        {activeTab === 'report' && (
          <DailyReport logs={logs} />
        )}
        
        {activeTab === 'database' && (
          <VehicleDatabase 
            vehicles={registeredVehicles}
            onAddVehicle={handleAddVehicle}
            onRemoveVehicle={handleRemoveVehicle}
          />
        )}
      </main>
    </div>
  );
};

export default App;